Feat/handle login session
IIC2513-2021-1/GudReads-front pull request #10
Opened 2021-06-29 03:45 UTC by dasolari

## What?
- Manejo de sesión en el frontend
- Se persiste la sesión con localStorage.

## Why?
- Para que puedan implementar el login en sus próximas entregas

## How?
- Se utilizó jwt-decode para obtener la fecha de expiración del token de usuario.
- Se utilizó localStorage para persistir la sesión del usuario.

2021-06-29 23:51 UTC, sivicencio requested changes
Dejé varias sugerencias. Fui algo picky, sin embargo, creo que la feature lo amerita 😉

2021-06-29 23:51 UTC, sivicencio commented on .gitignore
> +.env
Línea en blanco faltante.
```suggestion
.env

```

2021-06-29 23:51 UTC, sivicencio commented on src/contexts/AuthContext.jsx
> +  const handleUserLogout = () => {
Si en `handleAutomaticLogout` estamos utilizando `useCallback`, creo que deberíamos también utilizarlo aquí y en `handleUserLogin`. Estos dos últimos debiesen tener un array de dependencias vacío.

2021-06-29 23:51 UTC, sivicencio commented on src/contexts/AuthContext.jsx
> +  }, []);
Aquí me parece que falta `history` como parte del array de dependencias. ¿ESLint no tiró errores?

2021-06-29 23:51 UTC, sivicencio commented on src/views/Home.jsx
> +          {currentUser?.firstName}
Bien ahí utilizando optional chaining 🤓

2021-06-29 23:51 UTC, sivicencio commented on src/views/Home.jsx
> +      <div>
Este `div` podría eliminarse, o bien ser reemplazado por un `header` o algo que le dé más significado.

2021-06-29 23:51 UTC, sivicencio commented on src/views/Home.jsx
> +            <h3>Logout from your current account in order to log in</h3>
Este `h3` no veo que aporte mucho. Decir "cierra sesión para poder iniciar sesión" es un poco extraño. Basta con colocar el botón que está bajo este elemento no más.

2021-06-29 23:51 UTC, sivicencio commented on src/views/Login.jsx
> +      body: JSON.stringify({ ...values }),
¿Alguna razón para crear un nuevo objeto al pasárselo como parámetro a `JSON.stringify`?

2021-06-29 23:51 UTC, sivicencio commented on src/views/Login.jsx
> +      setLoading(false);
Esto podría ir fuera y después del `try/catch` para que, en caso de error, también se setee `loading` como `false`.

2021-06-29 23:51 UTC, sivicencio commented on src/views/Login.jsx
> +      {currentUser && <Redirect to="/" />}
Esto podría extraerse del `return` y colocarse, por ejemplo, justo arriba del check del loading:
```javascript
if (currentUser) return <Redirect to="/" />;

if (loading) {
  return <h2>Loading...</h2>;
}
```
De esta manera, dentro del `return` sólo tendremos el código asociado a cuando no está el usuario logueado.

2021-06-29 23:51 UTC, sivicencio commented on src/views/AuthorDetail.jsx
> +          )}
Me parece que esta es la parte que es parte de este PR y lo otro tendrás que hacer merge con lo de la cápsula 31.

2021-06-29 23:51 UTC, sivicencio commented on src/views/AuthorList.jsx
> +          )}
Similar a mi comentario justo anterior, se viene merge y/o rebase para integrar esto.

2021-06-29 23:51 UTC, sivicencio commented on src/components/CreateAuthor.jsx
> +          .deserialize(data, (_error, author) => setAuthors((prevState) => [...prevState, author]));
Aquí podría ser mejor pasar como prop una función tipo `addAuthor`, que reciba como parámetro un author deserializado, entonces sólo se llamaría a `addAuthor(author)`:
```suggestion
          .deserialize(data, (_error, author) => addAuthor(author));
```

Luego en `<AuthorList />` defines esa función con lo que agregaste aquí:
```javascript
const addAuthor = (author) => setAuthors((prevState) => [...prevState, author]);
```
La razón es que `CreateAuthor` no debería saber del estado del padre, y al utilizar `setAuthors` de esta manera se está suponiendo que este componente sabe cómo actualizar el estado del padre, lo que genera un acomplamiento entre ambos.

2021-06-29 23:51 UTC, sivicencio commented on src/components/CreateAuthor.jsx
> +  }
Una sugerencia para aprovechar React al máximo 🤓
```suggestion
  const isDisabled = useMemo(
    () => !Boolean(values.firstName && values.lastName && values.birthDate),
    [values],
  );
```
Habría que importar `useMemo` de `react` y asegurarse de que ESLint acepta ese array de dependencias, o tiene que ser agregarse cada property de `values`

2021-06-29 23:56 UTC, dasolari commented on .gitignore
> +.env
👍

2021-06-29 23:57 UTC, dasolari commented on src/contexts/AuthContext.jsx
> +  }, []);
Nop, no tiró errores.

2021-06-29 23:59 UTC, dasolari commented on src/contexts/AuthContext.jsx
> +  const handleUserLogout = () => {
La razón por la que use useCallback fue porque `handleAutomaticLogin` está en el arreglo de dependencias del `useEffect`. De esta forma no se forma un `loop` de _renders_ infinito. Las otras dos funciones no están en este arreglo, por lo que no lo encontré necesario.

2021-06-30 00:01 UTC, sivicencio commented on src/contexts/AuthContext.jsx
> +  const handleUserLogout = () => {
Ok, dejémoslo así no más entonces.

2021-06-30 00:01 UTC, dasolari commented on src/views/Home.jsx
> +      <div>
Si, no me había dado cuenta. Ya lo eliminé.

2021-06-30 00:05 UTC, dasolari commented on src/views/Login.jsx
> +      body: JSON.stringify({ ...values }),
:man_facepalming: :man_facepalming: :man_facepalming:
No tengo idea por qué hice eso. Es exactamente lo mismo que darle `JSON.stringify(values)`. El sueño 😴 , perdón. Ya lo corregí.

2021-06-30 00:06 UTC, dasolari commented on src/views/Login.jsx
> +      body: JSON.stringify({ ...values }),
Y está en el video 🤦‍♂️

2021-06-30 00:10 UTC, dasolari commented on src/views/Login.jsx
> +      setLoading(false);
Lo dejé en un `finally` para ser más ordenado.

2021-06-30 00:11 UTC, dasolari commented on src/views/Login.jsx
> +      setLoading(false);
![Screen Shot 2021-06-29 at 20 11 12](https://user-images.githubusercontent.com/42161460/123883074-2a78cd80-d916-11eb-9575-210f9154acab.png)

2021-06-30 00:12 UTC, dasolari commented on src/views/Login.jsx
> +      {currentUser && <Redirect to="/" />}
Arreglado!

2021-06-30 00:16 UTC, dasolari commented on src/components/CreateAuthor.jsx
> +          .deserialize(data, (_error, author) => setAuthors((prevState) => [...prevState, author]));
Toda la razón. Ya lo corregí.

2021-06-30 00:19 UTC, dasolari commented on src/components/CreateAuthor.jsx
> +  }
Que buena! Conocía `memo` pero nunca había utilizado `useMemo`, por lo que no lo entendía bien.

2021-06-30 00:47 UTC, dasolari commented on src/views/AuthorDetail.jsx
> +          )}
Yep, ahí se viene su merge conflict

2021-06-30 00:50 UTC, dasolari commented on src/views/AuthorDetail.jsx
> +          )}
Hay que realizarlo cuando se haga merge de #9

2021-06-30 16:04 UTC, dasolari commented
Cambios _mergeados_ y probados @sivicencio.

2021-06-30 21:21 UTC, sivicencio approved these changes
Gran trabajo 🎉

2021-06-30 21:24 UTC, merged