Cápsula formik
IIC2513-2021-1/GudReads-front pull request #12
Opened 2021-07-04 19:26 UTC by aljara97

Se agrega la vista `SignUp` implementada en la cápsula 33, también se modifica la vista de `Home` para referenciar al formulario de registro. También cambian archivos correspondientes a paquetes, ya que, se instalaron las librerías `yup` y `formik`.

2021-07-05 03:04 UTC, sivicencio requested changes
En general se ve bien 👍🏼
Dejé unos pocos cambios y sugerencias.

2021-07-05 03:04 UTC, sivicencio commented on src/views/Home.jsx
> +            <h3>Dont have an account yet? Sign Up</h3>
```suggestion
            <h3>Don't have an account yet? Sign Up</h3>
```

2021-07-05 03:04 UTC, sivicencio commented on src/views/SignUp.jsx
> +            .max(15, 'Your lastname must be 15 characters or less')
```suggestion
            .min(2, 'Your last name must be at least 2 characters')
            .max(15, 'Your last name must be 15 characters or less')
```

2021-07-05 03:04 UTC, sivicencio commented on src/views/SignUp.jsx
> +              ) : null}
Esto podría ser con un short-circuit, al igual que los otros campos.
```suggestion
              {errors.firstName && touched.firstName && (
                <div>{errors.firstName}</div>
              )}
```

2021-07-05 03:04 UTC, sivicencio commented on src/views/SignUp.jsx
> +            if (!response.ok) {
Creo que en este caso, a pesar de que `response.ok` será `true` para cualquier status en el rango de `2xx` (y por lo tanto `false` en este caso al estar negado), vale la pena ser más explícito en que esperamos `response.status !== 201` para setear un error.

2021-07-05 03:04 UTC, sivicencio commented on src/views/SignUp.jsx
> +            setMessage('User has been sucesesfully created');
```suggestion
            setMessage('User has been successfully created');
```

2021-07-06 02:26 UTC, aljara97 commented on src/views/SignUp.jsx
> +            .max(15, 'Your lastname must be 15 characters or less')
Listo, lo cambié según lo sugerido

2021-07-06 02:26 UTC, aljara97 commented on src/views/SignUp.jsx
> +              ) : null}
Se implementó como un short-circuit para todos los campos

2021-07-06 02:27 UTC, sivicencio approved these changes

2021-07-06 02:28 UTC, aljara97 commented on src/views/SignUp.jsx
> +            setMessage('User has been sucesesfully created');
También lo cambié, probablemente fue un error de tipeo 😄

2021-07-06 02:29 UTC, aljara97 commented on src/views/Home.jsx
> +            <h3>Dont have an account yet? Sign Up</h3>
En este caso, se arrojaba un error al hacer el cambio sugerido, por esa razón en un principio lo escribí como "Dont" en un principio, pero ahora lo cambié a "Do not"

2021-07-06 02:32 UTC, aljara97 commented on src/views/SignUp.jsx
> +            if (!response.ok) {
Listo, se maneja solo para es status 201

2021-07-06 02:32 UTC, merged